### ISSUE TITLE
Activate page goes to blank page after submit

### ISSUE THREAD

**Issue by htot** [edison-fw/edison-oobe#11]
More over: it would be nice if there was sort of a summary what will be changed after pressing Submit

**Comment by mwallnoefer** [comment]
Let's leave that as an extension. First I would like to understand the other issues (e.g. with mraa).

**Comment by htot** [comment]
@mwallnoefer I have merged your work so far into master. Thanks for all this. You are now the top committer to oobe :-)

**Comment by mwallnoefer** [comment]
One more thing: please don't forget to merge PR #13 as well.

**Comment by mwallnoefer** [comment]
Patch proposal (may of course be extended): https://github.com/mwallnoefer/edison-oobe/commit/6db8ed82cc9e081bd6e9f79539c07ee22ef2fd04

**Comment by htot** [comment]
I like it and pushed. Also fixed my stupid "Done" message after activation. You might want to rebase to 3d0e16e3

**Comment by mwallnoefer** [comment]
I think this should be closed .

**Comment by htot** [comment]
Thanks
