### ISSUE TITLE
"configure_edison --wifi" doesn't work

### ISSUE THREAD

**Issue by alext-mkrs** [edison-fw/edison-oobe#3]
From #2 (courtesy of @htot):

-----------------------------------------

Still `configure_edison --wifi` doesn't work. The reason is `wpa_cli scan` returns:
`Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory`

This interface also may need replacement (quick googled). 

`connmanctl scan wifi && connmanctl services` works, but does not show the bssid / frequency /signal level / encryption flags / ssid `wpi_cli` does. We can retrieve them with `connmanctl service --properties <service> `.
Or we could use `iw`, I found this one liner:
`iw dev wlan0 scan | egrep "signal|SSID" | sed -e "s/\tsignal: //" -e "s/\tSSID: //" | awk '{ORS = (NR % 2 == 0)? "\n" : " "; print}' | sort` which outputs:
```
-58.00 dBm TP-LINK_941F4A
-68.00 dBm Oranje Plantage 35 2.4G
-74.00 dBm 
-79.00 dBm Oranje Plantage 35 5G
-80.00 dBm ANNE
-85.00 dBm H369A6D5E05
-88.00 dBm Ziggo
```
Not too bad. What do you think?

-----------------------------------------

We've agreed I'll take a look into this and this issue is to track the task.

**Comment by mwallnoefer** [comment]
I have fixed this in my patches which will be merged soon. So stay tuned...

**Comment by mwallnoefer** [comment]
This should be closed I think.

**Comment by htot** [comment]
No, sorry I haven't made much progress. Family matters consumed a bit of time. I will continue to work on your patches after summer and after finishing the btrfs stuff. In the mean time, let's keep this as a reminder...

**Comment by mwallnoefer** [comment]
@alext-mkrs Okay in the meantime my patches have been merged so please re-test!

**Comment by mwallnoefer** [comment]
I guess that we may definitely close this now, the *cli* has been working since last spring.
